### ISSUE TITLE
Rewrite to .NET Core or PowerShell

### ISSUE THREAD

**Issue by FayneAldan** [FayneAldan/RASystemChecker#2]
Just a thought, but I might rewrite this script in .NET Core or PowerShell Core (both options cross-platform) to remove dependency on Node.

**Comment by blontic** [comment]
Wouldn't that then make a dependency on Windows?

**Comment by RuiNtD** [comment]
Nope. .NET Core and powershell are both cross platform.

**Comment by RuiNtD** [comment]
I no longer wish to rewrite this for .NET Core or PowerShell. I might rewrite for Deno at some point.
